# Generated by Django 2.1.4 on 2024-12-01 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('img', models.ImageField(default=None, null=True, upload_to='img/')),
                ('doc', models.FileField(default=None, null=True, upload_to='doc/')),
                ('choice', models.IntegerField(choices=[(1, 'Abc'), (2, 'Bcd'), (3, 'Cde')], default=1)),
                ('message', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Forms',
            },
        ),
    ]
