# Generated by Django 2.1.4 on 2024-10-17 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='choice',
            field=models.CharField(choices=[('A', 'abc'), ('C', 'cde'), ('B', 'bcd')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='form',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
