# Generated by Django 2.1.4 on 2024-10-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='doc',
            field=models.FileField(default=None, null=True, upload_to='doc/'),
        ),
        migrations.AddField(
            model_name='form',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='form',
            name='choice',
            field=models.CharField(choices=[('B', 'bcd'), ('C', 'cde'), ('A', 'abc')], default='A', max_length=1),
        ),
    ]
